### ISSUE TITLE
Implement the `kbuild` tool

### ISSUE THREAD

**Issue by tothtamas28** [runtimeverification/pyk#30]
Right now, the K Framework lacks support for dependency management between K projects. The following description proposes a tool, `kbuild`, to address the need.

`kbuild` supports two main features:
* Installation and management of binaries for multiple versions of the K Framework (related: https://github.com/runtimeverification/k/issues/2894)
* Dependency management for K projects

# Preliminaries

A `kbuild` project is a folder with a file `kbuild.toml` in its root that defines: 

* Project metadata (name, description, version, constraints on K version, ...).
* Dependencies to other `kbuild` projects.
* Build targets that describe how  the project's definitions can be kompiled.
* Command targets that describe how other K tools (in particular, `kprove` and `krun`) can be invoked on the project or it's dependencies.

The `kbuild` CLI and Python library let's the user interact with the project in various ways

* `kbuild` - kompile all build targets
* `kbuild <build-target>` - kompile and install `<build-target>`
* `kbuild run <command-target>` - execute `<command-target>`

`kbuild` manages all its artifacts in a folder under the user's home (e.g. in `~/.kbuild`), called the `kbuild` folder.

# Example

Below is an example that describes `kbuild` features in more detail.

## Project configuration

An example `kbuild.toml` configuration could look as follows.

```toml
[project]
k = ">=5.3.0"
title = "foundry-semantics"
version = "0.1.0"
description = "K semantics for the Foundry toolkit"
includes = "./includes"
resources = "./resources"

[dependencies.evm-semantics]
repo = "https://github.com/runtimeverification/evm-semantics"
rev = "v1.0.1-a7e1c8b"

[builds.default]
backend = "haskell"
main-file = "foundry.k"
main-module = "FOUNDRY"

[commands.prove]
build = "default"
tool = "kprove"
spec-file = "./specs/test-spec.k"
concrete-rules-file = "./concrete-rules.txt"

[commands.test-kevm]
build = "evm_semantics.haskell"
tool = "kprove"
spec-file = "./specs/test-kevm-spec.k"
```

## Building the project

Building a target does the following.

1. `kbuild` checks if an up-to-date version of the target has already been kompiled and installed in the `kbuild` folder. If so, compilation is done. (**Comment**: currently we achieve this with `make`.)

2. `kbuild` checks if any version of K satisfying the version constraints is installed in the `kbuild` folder. If not, it pulls a version for the given platform into the `kbuild` folder. (**Comment**: currently we achieve this with `git` submodules.)

3. `kbuild` checks each dependency, and pulls a corresponding version for each into the `kbuild` folder if needed.

4. `kbuild` sets up K.

5. `kbuild` kompiles the target and installs it under the `kbuild` folder with proper folder structure and naming.

For `kbuild default`, the resulting layout in the `kbuild` folder could look something like this:

```
.kbuild
├─ evm-semantics-v1.0.1-a7e1c8b
│  ├─ includes
│  ├─ resources
│  └─ manifest.toml
├─ foundry-semantics-0.1.0
│  ├─ includes
│  ├─ default-5.3.198
│  ├─ resources
│  └─ manifest.toml
└─ k
   └─ kframework-5.3.198
```

where

* Folder `k` contains installations of the K Framework.
* The other folders are installed `kbuild` projects, where
   * `includes` contains `k` source files for `requires`.
   * `resources` contains other source files that targets might refer to.
   * The other folders are definitions kompiled according to build targets, labeled with a K version used for kompilation.
   * `manifest.toml` is a descriptor for the installation (in the first iteration it can have the same contents as `kbuild.toml`).

## Running commands

Running a command target involves building its build target, setting up K, then running the specified command with the given arguments against the corresponding kompiled definition, includes and resources.

For example,

```bash
kbuild run prove
```

translates to

```bash
~/.kbuild/k/kframework-5.3.198/bin/kprove  ~/.kbuild/foundry-semantics-0.1.0/resources/specs/test-spec.k \
    --definition ~/.kbuild/foundry-semantics-0.1.0/default-5.3.198 \
    -I ~/.kbuild/foundry-semantics-0.1.0/includes \
    -I ~/.kbuild/evm-semantics-v1.0.1-a7e1c8b/includes \
    --concrete-rules-file ~/.kbuild/foundry-semantics-0.1.0/resources/concrete-rules.txt
```

# Further ideas

* `kbuild` should admit parametric targets.
