### ISSUE TITLE
Debug data in the KCFG viewer

### ISSUE THREAD

**Issue by goodlyrottenapple** [runtimeverification/pyk#393]
The booster backend includes a lot of granular tracing of everything happening during rewrite, including failed unfication/matches and simplification/function evaluation of terms and side-conditions. Because the development of the simplifier is getting ricky, we would like to integrate all this debugging data into the KCFG viewer. This will be useful not only to the haskell team but also the end users, who could use the debug mode to trace why e.g. a certain simplification rule isn't being applied, etc.
This proposal supersedes https://github.com/runtimeverification/haskell-backend/issues/3561 in that the booster should support the above plus a much finer-grained tracing info.

## RPC protocol changes

When one of the following flags: `log_successful_rewrites`, `log_failed_rewrites`, `log_successful_rsimplifications` or `log_failed_simplifications` are sent with the execute/simplify request, the backends should return a `log` (or similar) object as part of the response. The response should in fact be an array of rewrite/simplify traces, with the following format:

### rewrite success

if a semantic rule succeeds, yields

```yaml
tag: rewrite_success
rewritten_term: <optional CTerm>
rule_id: <unique_id>
```

the `rewritten_term` is optional as it may not be present when executing with the old backend (unclear how difficult it would be to implement)

### rewrite failure

if a rule fails to apply, the backend will emit

```yaml
tag: rewrite_failure
reason : <string>
rule_id: <unique_id>
```

### simplification
The booster distinguishes between concrete and symbolic simplification and we want to be able to tell which one was applied and how often, therefore we can have either of the two traces

```yaml
tag: llvm_simplification
original_term : <KInner>
result : <SimplificationResult>
```

```yaml
tag: simplification
original_term : <optional KInner>
result : <SimplificationResult>
```

where `original_term` may be optional when coming from the old backend and the `SimplificationResult` object can be one of the following:

```yaml
tag: success
rewritten_term : <optional KInner>
rule_id: <unique_id>
```

where the `rewritten_term` is optional for the old backend and `rule` is optional because when calling the LLVM backend, we have no way of obtaining this information (the LLVM backend can in fact apply many rules in sequence)

```yaml
tag: failure
reason: <string>
rule_id: <unique_id>
```

This schema should cover the use-cases of the original issue as well as provide a detailed view of all the intermediate rewrite steps and simplifications.

## Pyk data representation changes

Not sure about this part, @ehildenb @tothtamas28 please comment. From looking at the code, it would seem the easiest thing to do would be to extend a node in the KCFG tree with a debug list, which mirrors the response schema above and stores all the intermediate debug information. then, in the kcfg viewer, we could have a drop-down/toggle for each node or a global toggle, which would expand the debug info and add it to the tree between the previous and current node. We could use color to distinguish rewrite steps from simplification
